
package com.bloodbankmanagement.view;





/**
 *
 * @author prabinkumargupta
 */
public class MainDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form MainDashBoard
     */
    public MainDashBoard() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlMainBackground = new javax.swing.JPanel();
        pnlHeadingTitle = new javax.swing.JPanel();
        lblHeadingTitle = new javax.swing.JLabel();
        lblSubHeading = new javax.swing.JLabel();
        lblBloodIcon = new javax.swing.JLabel();
        jbtnLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jpDashboardList = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        pnlSubTitle = new javax.swing.JPanel();
        lblWelcomeBloodBankTitle = new javax.swing.JLabel();
        lblBloodIconHand = new javax.swing.JLabel();
        lblMiddle = new javax.swing.JLabel();
        lblSubMiddle = new javax.swing.JLabel();
        lblFooterTitle = new javax.swing.JLabel();
        lblFooterTitle1 = new javax.swing.JLabel();
        pnlDonorList = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlDonorDetail = new javax.swing.JPanel();
        lblDonorForm = new javax.swing.JLabel();
        lblDonorId = new javax.swing.JLabel();
        tfAge = new javax.swing.JTextField();
        tfFullName = new javax.swing.JTextField();
        lblfullname = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        tfDonorId = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        tfContact = new javax.swing.JTextField();
        lblBloodGroup = new javax.swing.JLabel();
        jcbBloodGroup = new javax.swing.JComboBox<>();
        lblAddress = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        jcbGender = new javax.swing.JComboBox<>();
        tfAge2 = new javax.swing.JTextField();
        jbtnClear = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jspInformationTable = new javax.swing.JScrollPane();
        jtblInformationTable = new javax.swing.JTable();
        pnlContactUs = new javax.swing.JPanel();
        pnlImageBlood = new javax.swing.JPanel();
        lblBloodImg = new javax.swing.JLabel();
        pnlMainContact = new javax.swing.JPanel();
        pnlContactDetails = new javax.swing.JPanel();
        lblContactUs = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblCallUs = new javax.swing.JLabel();
        lblSendMessage = new javax.swing.JLabel();
        lblCallImg = new javax.swing.JLabel();
        lblMessageImg = new javax.swing.JLabel();
        lblAdressImg = new javax.swing.JLabel();
        lblAddressDetail = new javax.swing.JLabel();
        lblMessageDetail = new javax.swing.JLabel();
        lblCallingDetails = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Dashboard"); // NOI18N

        pnlMainBackground.setSize(new java.awt.Dimension(700, 500));

        pnlHeadingTitle.setBackground(new java.awt.Color(255, 255, 255));

        lblHeadingTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblHeadingTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblHeadingTitle.setForeground(new java.awt.Color(204, 0, 51));
        lblHeadingTitle.setText("Blood Bank Management System");

        lblSubHeading.setBackground(new java.awt.Color(204, 0, 0));
        lblSubHeading.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblSubHeading.setForeground(new java.awt.Color(204, 0, 0));
        lblSubHeading.setText("Donate Blood Save Life");

        lblBloodIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bloodbankmanagement/view/resource/blood-bank.png"))); // NOI18N

        jbtnLogOut.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jbtnLogOut.setForeground(new java.awt.Color(153, 0, 0));
        jbtnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bloodbankmanagement/view/resource/logout-removebg-preview.png"))); // NOI18N
        jbtnLogOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogOutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("LOGOUT");

        javax.swing.GroupLayout pnlHeadingTitleLayout = new javax.swing.GroupLayout(pnlHeadingTitle);
        pnlHeadingTitle.setLayout(pnlHeadingTitleLayout);
        pnlHeadingTitleLayout.setHorizontalGroup(
            pnlHeadingTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadingTitleLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblBloodIcon)
                .addGap(39, 39, 39)
                .addGroup(pnlHeadingTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeadingTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(320, 320, 320)
                .addGroup(pnlHeadingTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnLogOut)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        pnlHeadingTitleLayout.setVerticalGroup(
            pnlHeadingTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingTitleLayout.createSequentialGroup()
                .addGroup(pnlHeadingTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeadingTitleLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblHeadingTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSubHeading))
                    .addGroup(pnlHeadingTitleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlHeadingTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlHeadingTitleLayout.createSequentialGroup()
                                .addComponent(jbtnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBloodIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpDashboardList.setBackground(new java.awt.Color(255, 255, 255));

        pnlHome.setBackground(new java.awt.Color(204, 0, 51));

        lblWelcomeBloodBankTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        lblWelcomeBloodBankTitle.setText("Welcome To Blood Bank & Donor Management System");

        javax.swing.GroupLayout pnlSubTitleLayout = new javax.swing.GroupLayout(pnlSubTitle);
        pnlSubTitle.setLayout(pnlSubTitleLayout);
        pnlSubTitleLayout.setHorizontalGroup(
            pnlSubTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubTitleLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lblWelcomeBloodBankTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSubTitleLayout.setVerticalGroup(
            pnlSubTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubTitleLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblWelcomeBloodBankTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        lblBloodIconHand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bloodbankmanagement/view/resource/bloodIcon_Hand.png"))); // NOI18N

        lblMiddle.setFont(new java.awt.Font("Serif", 0, 28)); // NOI18N
        lblMiddle.setForeground(new java.awt.Color(255, 255, 255));
        lblMiddle.setText("The blood you donate gives someone");

        lblSubMiddle.setFont(new java.awt.Font("Serif", 0, 28)); // NOI18N
        lblSubMiddle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubMiddle.setText("another chance at life.");

        lblFooterTitle.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        lblFooterTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblFooterTitle.setText("GIVE THE GIFT OF LIFE");

        lblFooterTitle1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lblFooterTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblFooterTitle1.setText("DONATE BLOOD");

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblSubMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addContainerGap(133, Short.MAX_VALUE)
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                                .addComponent(lblFooterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                                .addComponent(lblFooterTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                                .addComponent(lblMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))))
                .addComponent(lblBloodIconHand, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addGap(98, 98, Short.MAX_VALUE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addComponent(lblMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSubMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(lblFooterTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFooterTitle1)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addComponent(lblBloodIconHand, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(pnlSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpDashboardList.addTab("Home", pnlHome);

        pnlDonorList.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 0, 51));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Donor Information Table");

        pnlDonorDetail.setBackground(new java.awt.Color(204, 0, 51));
        pnlDonorDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblDonorForm.setBackground(new java.awt.Color(0, 0, 0));
        lblDonorForm.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblDonorForm.setForeground(new java.awt.Color(255, 255, 255));
        lblDonorForm.setText("Donor Data Form");
        lblDonorForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblDonorId.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        lblDonorId.setForeground(new java.awt.Color(255, 255, 255));
        lblDonorId.setText("Donor Id");

        tfAge.setBackground(new java.awt.Color(0, 0, 0));
        tfAge.setForeground(new java.awt.Color(255, 255, 255));

        tfFullName.setBackground(new java.awt.Color(0, 0, 0));
        tfFullName.setForeground(new java.awt.Color(255, 255, 255));

        lblfullname.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        lblfullname.setForeground(new java.awt.Color(255, 255, 255));
        lblfullname.setText("Full Name");

        lblAge.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText("Age ");

        tfDonorId.setBackground(new java.awt.Color(0, 0, 0));
        tfDonorId.setForeground(new java.awt.Color(255, 255, 255));

        lblContact.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        lblContact.setForeground(new java.awt.Color(255, 255, 255));
        lblContact.setText("Contact");

        tfContact.setBackground(new java.awt.Color(0, 0, 0));
        tfContact.setForeground(new java.awt.Color(255, 255, 255));

        lblBloodGroup.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        lblBloodGroup.setForeground(new java.awt.Color(255, 255, 255));
        lblBloodGroup.setText("Blood Group");

        jcbBloodGroup.setBackground(new java.awt.Color(0, 0, 0));
        jcbBloodGroup.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jcbBloodGroup.setForeground(new java.awt.Color(255, 255, 255));
        jcbBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "O+", "B+", "AB+", "A-", "O-", "B-", "AB-" }));
        jcbBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBloodGroupActionPerformed(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Address");

        tfAddress.setBackground(new java.awt.Color(0, 0, 0));
        tfAddress.setForeground(new java.awt.Color(255, 255, 255));

        lblEmail.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");

        lblEmail1.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        lblEmail1.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail1.setText("Gender");

        jcbGender.setBackground(new java.awt.Color(0, 0, 0));
        jcbGender.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jcbGender.setForeground(new java.awt.Color(255, 255, 255));
        jcbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        tfAge2.setBackground(new java.awt.Color(0, 0, 0));
        tfAge2.setForeground(new java.awt.Color(255, 255, 255));

        jbtnClear.setBackground(new java.awt.Color(0, 0, 0));
        jbtnClear.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jbtnClear.setForeground(new java.awt.Color(255, 255, 255));
        jbtnClear.setText("CLEAR");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jbtnAdd.setBackground(new java.awt.Color(0, 0, 0));
        jbtnAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jbtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAdd.setText("ADD");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jbtnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        jbtnUpdate.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jbtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jbtnUpdate.setText("UPDATE");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jbtnDelete.setBackground(new java.awt.Color(0, 0, 0));
        jbtnDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jbtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDelete.setText("DELETE");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDonorDetailLayout = new javax.swing.GroupLayout(pnlDonorDetail);
        pnlDonorDetail.setLayout(pnlDonorDetailLayout);
        pnlDonorDetailLayout.setHorizontalGroup(
            pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDonorDetailLayout.createSequentialGroup()
                .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDonorDetailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDonorId, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAge2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDonorId, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblContact, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(tfContact))
                            .addComponent(jcbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlDonorDetailLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDonorDetailLayout.createSequentialGroup()
                                        .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDonorDetailLayout.createSequentialGroup()
                                        .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDonorDetailLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10))))
                    .addGroup(pnlDonorDetailLayout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(lblDonorForm, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        pnlDonorDetailLayout.setVerticalGroup(
            pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDonorDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDonorDetailLayout.createSequentialGroup()
                        .addComponent(lblDonorForm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDonorId)
                            .addComponent(lblfullname)
                            .addComponent(lblBloodGroup))
                        .addGap(3, 3, 3)
                        .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDonorId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(lblContact)))
                    .addGroup(pnlDonorDetailLayout.createSequentialGroup()
                        .addComponent(lblAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDonorDetailLayout.createSequentialGroup()
                        .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblEmail1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfAge2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tfContact, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pnlDonorDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jtblInformationTable.setBackground(new java.awt.Color(102, 102, 0));
        jtblInformationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Donor Id", "Full Name", "Age", "Contact", "Blood Group", "Address", "Email", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jspInformationTable.setViewportView(jtblInformationTable);
        if (jtblInformationTable.getColumnModel().getColumnCount() > 0) {
            jtblInformationTable.getColumnModel().getColumn(0).setResizable(false);
            jtblInformationTable.getColumnModel().getColumn(2).setResizable(false);
            jtblInformationTable.getColumnModel().getColumn(3).setResizable(false);
            jtblInformationTable.getColumnModel().getColumn(4).setResizable(false);
            jtblInformationTable.getColumnModel().getColumn(5).setResizable(false);
            jtblInformationTable.getColumnModel().getColumn(6).setResizable(false);
            jtblInformationTable.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout pnlDonorListLayout = new javax.swing.GroupLayout(pnlDonorList);
        pnlDonorList.setLayout(pnlDonorListLayout);
        pnlDonorListLayout.setHorizontalGroup(
            pnlDonorListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDonorListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDonorListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDonorListLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jspInformationTable, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                    .addComponent(pnlDonorDetail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDonorListLayout.setVerticalGroup(
            pnlDonorListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDonorListLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspInformationTable, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDonorDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpDashboardList.addTab("Donor List", pnlDonorList);

        pnlImageBlood.setBackground(new java.awt.Color(204, 0, 51));

        lblBloodImg.setBackground(new java.awt.Color(204, 0, 0));
        lblBloodImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bloodbankmanagement/view/resource/bloodnonate-removebg.png"))); // NOI18N

        javax.swing.GroupLayout pnlImageBloodLayout = new javax.swing.GroupLayout(pnlImageBlood);
        pnlImageBlood.setLayout(pnlImageBloodLayout);
        pnlImageBloodLayout.setHorizontalGroup(
            pnlImageBloodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImageBloodLayout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(lblBloodImg, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlImageBloodLayout.setVerticalGroup(
            pnlImageBloodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImageBloodLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBloodImg, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlMainContact.setBackground(new java.awt.Color(0, 0, 0));

        pnlContactDetails.setBackground(new java.awt.Color(204, 0, 51));
        pnlContactDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        pnlContactDetails.setForeground(new java.awt.Color(255, 255, 255));

        lblContactUs.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        lblContactUs.setForeground(new java.awt.Color(255, 255, 255));
        lblContactUs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContactUs.setText("CONTACT US");

        lblLocation.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblLocation.setText("Address:");

        lblCallUs.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lblCallUs.setForeground(new java.awt.Color(255, 255, 255));
        lblCallUs.setText("Call Us:");

        lblSendMessage.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblSendMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblSendMessage.setText("Send Message:");

        lblCallImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bloodbankmanagement/view/resource/contact-information.png"))); // NOI18N

        lblMessageImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bloodbankmanagement/view/resource/new-email.png"))); // NOI18N
        lblMessageImg.setText("jLabel3");

        lblAdressImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bloodbankmanagement/view/resource/location-pin.png"))); // NOI18N

        lblAddressDetail.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblAddressDetail.setForeground(new java.awt.Color(255, 255, 255));
        lblAddressDetail.setText("29, Anamnagar,st.Kathmandu Nepal");

        lblMessageDetail.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblMessageDetail.setForeground(new java.awt.Color(255, 255, 255));
        lblMessageDetail.setText("donatebloodnepal091@gmail.com");

        lblCallingDetails.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblCallingDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblCallingDetails.setText("+977-9812032423");

        javax.swing.GroupLayout pnlContactDetailsLayout = new javax.swing.GroupLayout(pnlContactDetails);
        pnlContactDetails.setLayout(pnlContactDetailsLayout);
        pnlContactDetailsLayout.setHorizontalGroup(
            pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(lblContactUs, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                                .addComponent(lblAdressImg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAddressDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMessageImg, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCallImg))
                                .addGap(18, 18, 18)
                                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                                        .addComponent(lblCallUs, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCallingDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                                        .addComponent(lblSendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMessageDetail)))))))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        pnlContactDetailsLayout.setVerticalGroup(
            pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCallUs)
                        .addComponent(lblCallingDetails))
                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                        .addComponent(lblContactUs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblLocation)
                                .addComponent(lblAddressDetail))
                            .addComponent(lblAdressImg))
                        .addGap(38, 38, 38)
                        .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSendMessage)
                                .addComponent(lblMessageDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMessageImg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(lblCallImg)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bloodbankmanagement/view/resource/pointingdetails-removebg.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout pnlMainContactLayout = new javax.swing.GroupLayout(pnlMainContact);
        pnlMainContact.setLayout(pnlMainContactLayout);
        pnlMainContactLayout.setHorizontalGroup(
            pnlMainContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainContactLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlContactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainContactLayout.setVerticalGroup(
            pnlMainContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContactLayout.createSequentialGroup()
                .addGroup(pnlMainContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainContactLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(pnlContactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainContactLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel3)))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContactUsLayout = new javax.swing.GroupLayout(pnlContactUs);
        pnlContactUs.setLayout(pnlContactUsLayout);
        pnlContactUsLayout.setHorizontalGroup(
            pnlContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlImageBlood, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMainContact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlContactUsLayout.setVerticalGroup(
            pnlContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactUsLayout.createSequentialGroup()
                .addComponent(pnlImageBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMainContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpDashboardList.addTab("Contact Us", pnlContactUs);

        javax.swing.GroupLayout pnlMainBackgroundLayout = new javax.swing.GroupLayout(pnlMainBackground);
        pnlMainBackground.setLayout(pnlMainBackgroundLayout);
        pnlMainBackgroundLayout.setHorizontalGroup(
            pnlMainBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeadingTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpDashboardList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnlMainBackgroundLayout.setVerticalGroup(
            pnlMainBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainBackgroundLayout.createSequentialGroup()
                .addComponent(pnlHeadingTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpDashboardList, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBloodGroupActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogOutActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jbtnLogOutActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jbtnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        // Login Screen
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDashBoard().setVisible(true);
            }
        });
        // Login Screen 
        Login login = new Login();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnLogOut;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<String> jcbBloodGroup;
    private javax.swing.JComboBox<String> jcbGender;
    private javax.swing.JTabbedPane jpDashboardList;
    private javax.swing.JScrollPane jspInformationTable;
    private javax.swing.JTable jtblInformationTable;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddressDetail;
    private javax.swing.JLabel lblAdressImg;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblBloodIcon;
    private javax.swing.JLabel lblBloodIconHand;
    private javax.swing.JLabel lblBloodImg;
    private javax.swing.JLabel lblCallImg;
    private javax.swing.JLabel lblCallUs;
    private javax.swing.JLabel lblCallingDetails;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblContactUs;
    private javax.swing.JLabel lblDonorForm;
    private javax.swing.JLabel lblDonorId;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblFooterTitle;
    private javax.swing.JLabel lblFooterTitle1;
    private javax.swing.JLabel lblHeadingTitle;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMessageDetail;
    private javax.swing.JLabel lblMessageImg;
    private javax.swing.JLabel lblMiddle;
    private javax.swing.JLabel lblSendMessage;
    private javax.swing.JLabel lblSubHeading;
    private javax.swing.JLabel lblSubMiddle;
    private javax.swing.JLabel lblWelcomeBloodBankTitle;
    private javax.swing.JLabel lblfullname;
    private javax.swing.JPanel pnlContactDetails;
    private javax.swing.JPanel pnlContactUs;
    private javax.swing.JPanel pnlDonorDetail;
    private javax.swing.JPanel pnlDonorList;
    private javax.swing.JPanel pnlHeadingTitle;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlImageBlood;
    private javax.swing.JPanel pnlMainBackground;
    private javax.swing.JPanel pnlMainContact;
    private javax.swing.JPanel pnlSubTitle;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfAge2;
    private javax.swing.JTextField tfContact;
    private javax.swing.JTextField tfDonorId;
    private javax.swing.JTextField tfFullName;
    // End of variables declaration//GEN-END:variables
}
