
package com.bloodbankmanagement.view;

import com.bloodbankmanagement.model.BloodBankModel;
import com.bloodbankmanagement.util.ValidationUtil;
import java.util.LinkedList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prabinkumargupta
 */
public class welcomeToBloodBank extends javax.swing.JFrame {

    
    private List<BloodBankModel> bloodBankList;
    private java.awt.CardLayout cardLayout;
    private final ValidationUtil validationUtil;
    /**
     * Creates new form WelcomeToBloodBank
     */
    public welcomeToBloodBank() {
        setResizable(false);
        initComponents();
        validationUtil = new ValidationUtil();
        
        
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblHeadingTitle = new javax.swing.JLabel();
        lblSubHeading = new javax.swing.JLabel();
        lblSubHeading1 = new javax.swing.JLabel();
        jpbLoadingScreen = new javax.swing.JProgressBar();
        lblLoading = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlMain.setBackground(new java.awt.Color(204, 0, 51));
        pnlMain.setForeground(new java.awt.Color(255, 255, 255));

        lblHeadingTitle.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        lblHeadingTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeadingTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeadingTitle.setText("Welcome To Blood Bank Nepal");

        lblSubHeading.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        lblSubHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblSubHeading.setText("Donate Blood Save Life");

        lblSubHeading1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 22)); // NOI18N
        lblSubHeading1.setForeground(new java.awt.Color(255, 255, 255));
        lblSubHeading1.setText("Nepal's Number One Blood Bank");

        lblLoading.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblLoading.setForeground(new java.awt.Color(255, 255, 255));
        lblLoading.setText("Loading...");

        lblLogo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bloodbankmanagement/view/resource/blooddonationiconpng (1).png"))); // NOI18N

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeadingTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpbLoadingScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubHeading1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(lblSubHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 334, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeadingTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubHeading1)
                .addGap(39, 39, 39)
                .addComponent(lblLoading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpbLoadingScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomeToBloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomeToBloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomeToBloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomeToBloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        welcomeToBloodBank welcome = new welcomeToBloodBank();
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                welcome.setVisible(true);
            }
        });
        //
        try{
            for(int i=0; i<=100; i++){
                Thread.sleep(30);
                welcome.jpbLoadingScreen.setValue(i); 
                
                
                
                
            }
        }catch(Exception e){
            
        }
        // Login Screen 
        Login login = new Login();
        // close welcome page before open login
        welcome.setVisible(false);
        login.setVisible(true); // Display login Screen
        
        // close welcomepage
        welcome.dispose();
        
        
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jpbLoadingScreen;
    private javax.swing.JLabel lblHeadingTitle;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSubHeading;
    private javax.swing.JLabel lblSubHeading1;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
